version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
  test:
    working_directory: ~/program-service/src
    docker:
      - image: cimg/node:13.10.0
      - image: circleci/postgres:9.6-alpine
        auth:
          username: ahghatol
          password: pw4amolg123  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sunbird_programs
    steps:
      - checkout:
          path: ~/program-service
      - run: git submodule sync
      - run: git submodule update --init
      - run: node --version
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Install PSQL CLI; Import dummy data; run an example query
          command: psql -u postgres sunbird_programs < sql-data/dummy.sql
      - run:
          name: Remove Package Lock
          command: 'rm -f package-lock.json'
      - run:
          name: Installing npm deps
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: make directory & ng lint
          command: 'mkdir -p /tmp/logs'
      - run:
          name: Executing test cases
          command: 'npm run test-with-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
         name: run sonar scanner
         command: 'cd ~/program-service/src && sonar-scanner'

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      # - build
      - test
