version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
  test:
    working_directory: ~/program-service/src
    docker:
      - image: cimg/node:13.10.0
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: usrtestcases
          POSTGRES_PASSWORD: $sunbird_program_db_password
          POSTGRES_DB: $sunbird_program_db_name
    steps:
      - checkout:
          path: ~/program-service
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: ENV VAR 1
          command: echo $dbpwd;
      - run:
          name: ENV VAR 2
          command: |
                echo "POSTGRES_DB" $db
      - run:
          name: Install PSQL CLI; Import dummy data; run an example query
          command: |
              sudo apt-get update
              sudo apt-get install postgresql-client
              psql -U usrtestcases -h localhost -d postgres -c "CREATE DATABASE $sunbird_program_db_name"
              psql -U usrtestcases -h localhost --dbname=$sunbird_program_db_name < sql-data/dummy.sql
      - run:
          name: Remove Package Lock
          command: 'rm -f package-lock.json'
      - run:
          name: Installing npm deps
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: make directory & ng lint
          command: 'mkdir -p /tmp/logs'
      - run:
          name: Executing test cases
          command: 'npm run test-with-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Run sonar scanner
          command: | 
              sudo npm install -g sonarqube-scanner
              cd ../ && sonar-scanner

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      # - build
      - test
