version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout

  test:
    working_directory: ~/program-service/src
    docker:
      - image: cimg/node:13.10.0
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    #~ steps:
      #~ - checkout:
          #~ path: ~/program-service
      #~ - run: git submodule sync
      #~ - run: git submodule update --init
      #~ - run: node --version
      #~ - run:
          #~ name: Remove Package Lock
          #~ command: 'rm -f package-lock.json' 
      #~ - run:
          #~ name: Installing npm deps
          #~ command: 'npm install'
      #~ - save_cache:
          #~ key: dependency-cache-{{ checksum "package.json" }}
          #~ paths: ./node_modules
      #~ - run:
          #~ name: make directory & ng lint
          #~ command: 'mkdir -p /tmp/logs'
      #~ - run:
          #~ name: Executing test cases
          #~ command: 'npm run test-with-coverage | tee /tmp/logs/test_cases.log'
      #~ - run:
          #~ name: install sonar scanner
          #~ command: npm install -g sonarqube-scanner
      #~ - run:
         #~ name: run sonar scanner
         #~ command: 'cd ~/program-service/src && sonar-scanner'

workflows:
  build_and_test:
    jobs:
      #~ - build
      - test
